# Setup
title: Sumin's Portfolio
description: "함께 일할 때 더 빛을 내는<br/><i>백엔드 개발자</i><br/><b>박수민</b>입니다."
url: https://sumaee.github.io
avatar: /assets/profile.jpg
paginate: 5
permalink: pretty
cover_image: /assets/bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: sumin
#   card: summary
logo: logo.png
social:
  name: Sumin Park
  links:
    - https://blog.naver.com/1379psm
    - https://github.com/sumaee
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Sumin Park
  url: https://sumaee.github.io
  email: 1379psm@naver.com
